/**
 * MIT License
 * <p>
 * Copyright (c) 2017-2018 nuls.io
 * <p>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * <p>
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * <p>
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package io.nuls.contract.airdrop;

/**
 * @author: PierreLuo
 * @date: 2020-02-27
 */
public class AddressFactory {

    protected String[] plAddressArray = {"NULSd6Hgf1dTFB9Szv1URmR3qvatRPSTi9fkQ",
            "NULSd6HgWVJC6md7z77kRNf5XgYzhhr9Cia2q",
            "NULSd6Hgga3y4ZDKAdTHmir6R8Xf3Uei1v7LR"};

    protected String[] tnxAddressArray = {"NULSd6HgXZqq1hj4WZY81mykbqgE7gfPrZ1eE",
            "NULSd6Hgi5rijUKtCjyJkEg8LrAvyMFwMiaZr",
            "NULSd6HgVqo1mug3rJ7dm2kan6KSghuJZa9LJ",
            "NULSd6HgdLs6KH8MU2wPfBeFUm6k4Ko8u6QBo",
            "NULSd6HghayBBMhg9GUJuEvfp2ebUnEhdAR8D",
            "NULSd6HgVfy172tQYEBYH8Z532t1aE9tXuzMj",
            "NULSd6HgYLAsGwM2NevxxHPnvwxnezkDrAS8f",
            "NULSd6HgXa6wsYTu55k9pSv2iGasmU65FVk2p",
            "NULSd6Hgb1UuyohnNeFwkeuGNH6h9RwfCWuEf",
            "NULSd6HgZKjnMegT6rjESBX2JoJUrvfanT9KG",
            "NULSd6HgdckXjSdkaY3be1adEv1wijfo2y14J",
            "NULSd6HgdusQ81yzJW6tNpa53ZmBrLn4fwgXD",
            "NULSd6HgiRjD6qENXu7o6nG8TN6pXiPkPNWNL",
            "NULSd6HgbSMjMH1eCmQKoT6GZDViR8yuPw5sX",
            "NULSd6Hgc5cXvVXDHW22pWH5nZDodyV6LvC1r",
            "NULSd6HgdZHohXQFq6sidGJJu3GoC5j5CUeZ8",
            "NULSd6HgjLiX8pm9dwjZsKLSSL8A7fP9vAXPX",
            "NULSd6HghhFbQFf5og2ePRLjKKs2FRhhMr1Sb",
            "NULSd6HgiSFpC49ga3e41recfJeLgmVfnnzuT",
            "NULSd6HgVYoQuPWJ5ufUrXHTJ7cenDbzzfxzG",
            "NULSd6Hget33N98o4YjY7QejgyZrGD297kMfZ",
            "NULSd6HgVXuSF3Ppz5DSLYD5v8m55igen5nji",
            "NULSd6HgbqCG2ut5eRzrswwCmyRYhHuEy7WQk",
            "NULSd6HgeSdXd268xvbCY6vaXf24ADzLouDe2",
            "NULSd6HgUxNzvRPabJdC2DRQBo6WYpFeUxocL",
            "NULSd6HgVoAwY7F3DHaWryqUq8HAKAhnVJDoj",
            "NULSd6HgckoMbuoYmuELTmeyfXa72ggwubjp8",
            "NULSd6HgegVDYZpQkXtNXzfkd3g7gHanecHZM",
            "NULSd6HgeDDvA4G3uj7xhjwfxHmyDmEbAj4cD",
            "NULSd6HgfCXvFYp88vxcEmHKri3oUWoyVrsaD",
            "NULSd6HgZ78dJWDhNFdBxMfUerxbjg8Ksp61A",
            "NULSd6HgVwEtRpWtz3DJo9W7EQ27S9YPutXg6",
            "NULSd6HgYghpgoQkeimFcYJZwvvDkTR7WpvZe",
            "NULSd6HgXk4o1os663ejapNf2w25rEJKnesHD",
            "NULSd6Hgch5VH5XJ62KRz8scNQdY6vmXQ2MJw",
            "NULSd6HgVDBMfbbCspdp5ityCvyQ9g7XSXr1A",
            "NULSd6HgbWs4nk1GEa1QWp1WxZfrqvemN31tZ",
            "NULSd6Hgb52RAbown4kwmCZn97MwHZ6cBsoLa",
            "NULSd6Hgdpp2qZCqjZide25zfX2VF6Chv7L9Q",
            "NULSd6HgXEEuaEATDV6vAKfFYdMh5T3a7As9M",
            "NULSd6HgXmAmNgYqNscPu5cCkKkyQwXL4C1zh",
            "NULSd6HgVwdHB4myQHTCiYBB9xVjZUM8d8T2R",
            "NULSd6HgX2j3YfW96UdgVPtefqqczWR7hQCZn",
            "NULSd6HgXKiHxU8kFsXqosy9ZUNMMCMVJ4DiH",
            "NULSd6HgeYoAGtw8v4qhWXkNSVPx9eNkmsQqN",
            "NULSd6Hgj6nBZMw3ySej323UsGHV8DpD3uo4J",
            "NULSd6HgZbG1FbDuVeXCQ49KHF8yNsvPn4KW4",
            "NULSd6HgcavjgR7ZhJt4iTLr96Y1nVZ1Konta",
            "NULSd6HgikndSsVQeqN5DkKcUTXAbJNdh8jMo",
            "NULSd6HggyET3NqoYuL4navbS4djBK4tkCePr",
            "NULSd6Hghez7hmWk7DyPPKszuPJV4bPJrs8YZ",
            "NULSd6HgXea1nPBskeNXE2rmGAY6CZo5ds9Z4",
            "NULSd6HgZn8QzYJvseFH4ATvFpKv2jZGX1C4C",
            "NULSd6Hgda5qHkk8JYrmkepLrnCyZGJdA6R3z",
            "NULSd6Hgh4ggXsByDi5SPLGPv7UyySEPG8eek",
            "NULSd6HgaLVaJ5fAv9TW2UH5GMvB1q7AEs2ac",
            "NULSd6Hgh9q53VH64TCgxZH8mkuaQ7qnFieRR",
            "NULSd6HgbeWLP1L2u6Ha7EFqjChFAyfYWyyh6",
            "NULSd6HgazP2nWD2XxtaW2XKKhN8jhFF94odJ",
            "NULSd6HgUEEGqs1DJiBge1PpiT1NWndKUTNoo",
            "NULSd6Hga8EkPnXv6YJA1oFvCYGTVSSoNinws",
            "NULSd6HgfBLXp3z1mo1dza4dcAadAusSB1gjd",
            "NULSd6HgZJwm8Ni5Fya3y8rUsmFPnb9VwimzY",
            "NULSd6HgYFxsNvahvD2SR1DTrvQJcFUENp4M4",
            "NULSd6Hgb7gosiqPBLarGZzuW1ALoRGAwbo15",
            "NULSd6Hgj2uqY3H1aMA5Ggj4dNMNugSwtdQTH",
            "NULSd6HgdvTydFNMBUkke9gpVZdjhZLKCnHCn",
            "NULSd6HgW8AvyJz1m5ZHRXRCpNcADXoyJ4PdV",
            "NULSd6Hgcbey5QEj4ej4evKg6aeH7g5uLTvhQ",
            "NULSd6HgioddBkcQP3mspMwE7L7q1rCYZG5Re",
            "NULSd6HgY15GQL8d1ZQZ1F95KJP77TkjyUHdJ",
            "NULSd6HghRfRN5F8GssQ4WukE52agf2QzoQrU",
            "NULSd6HgVumo87WEDYp3VfVw2aj5eNmYFRXdU",
            "NULSd6HgWD2GtcQtNbRuVYSvkn4mhQoRAx79f",
            "NULSd6HgYs53wWKZ62kscC3KNx3kEyubZKiot",
            "NULSd6HghJQmJapWkJ8huYRnZDZiu2bB2AXt1",
            "NULSd6HgZJfAsHmJsvasKsjB9PV3vYAp7GNyw",
            "NULSd6Hgc9x3xhU9TZGyicBWnZKhdSp6L9nok",
            "NULSd6HgbQ3k9EtLCdiuSxsFDrVUvMJrT9nqE",
            "NULSd6HgXvHR7NqAmfj4cVZNs7PFBv7HJu71v",
            "NULSd6HgjFBJFDPxvzNR1aiLppBE5RF9rKF2k",
            "NULSd6HgdwzZYKhg7sz2kPcW29vcvm7d8xPqp",
            "NULSd6HghHZMXoYhWjir92phWvyiwVAPQcK7t",
            "NULSd6HgZchGFUi1wCV49uDXu1dKEstyzi3SY",
            "NULSd6HgZNVPVkM32PSV5nFixgH4NaqzgbijA",
            "NULSd6HgU1c8wqYyyLKCZHGfLxei6nttYk9r8",
            "NULSd6HgccKZLRKFiuA48dqb5pE4p57h1wup7",
            "NULSd6Hgam8DNzKWUzttbgUYCjChKxC4MXbCR",
            "NULSd6HgimE8mCHnU8qADv7g841FPt5X5Hic1",
            "NULSd6HgengtkBmqtVFoYxmWt7fdfEqBM1aip",
            "NULSd6HgjJHh88H2SshEE54LqGe5Rx1iVZXXt",
            "NULSd6HgZMAa6Baz7c6LGxZpfzznNGfSxT5ir",
            "NULSd6HgiGkS6pVEjs8h7tYDeqybh7brpHxjX",
            "NULSd6Hgb1ddttSVBmtR9tfgV7xMo74UmAJab",
            "NULSd6HgXhjViFBW9xph3LzZYvG1cVxhoQkoR",
            "NULSd6HgWrY5cxuuugL8me8P1bUZiJTKeFVt7",
            "NULSd6HgcrQPqUcumjVK58kWrU8XK433C4QCy",
            "NULSd6HgcVrSdeE6J6YuRCWhZxGNbSZWzUpsA",
            "NULSd6HgcdadnrvQDU7gn3EWvv2dbPonhzjCA",
            "NULSd6HgdkfccngP5msecmZraTZF9mnLmxV8x",
            "NULSd6HgZuVoBGpcBTcSV9pUYEAgip1qnKign",
            "NULSd6HgjcF7MoMfBrUCmWk6YmyjjJ59QPhvZ",
            "NULSd6HghGckhNsxfrEajyNU5SPtUgAUqK32f",
            "NULSd6HgdQzPFmH951h6wwCogwbQNN1g8QK9K",
            "NULSd6HgXYM3oHUL34RThmwzautP3zwfaSSNN",
            "NULSd6HgVMm8TmyU9Tdjgax9N4Xi2bL2g1PrX",
            "NULSd6HghkUKUVhLmCtrD77ZQ5mqpcuxnnRNF",
            "NULSd6HgVhPQs7QyP5EUUhZpQFJEmuUKC5Qq2",
            "NULSd6Hgaq9iUqKpwuva5thBhV1HcYAGdMHpz",
            "NULSd6Hgce1ksTPRY7SdvG14HxDBCjzodLmvE",
            "NULSd6HgaxC9ESSYB2sRnPfTKagheRnyWzdLV",
            "NULSd6HgfwRo47EK69s1BspX2pkYxxj4x6Vhe",
            "NULSd6HgUckc4gmNgCgDbsnqx5a7n8QTUWNLu",
            "NULSd6HgcMiY6Zt3tzr6aT9Dk1hFS6ZXLKDfW",
            "NULSd6Hgdu7pYBbKfYDLefNesLDMcfogZt1hV",
            "NULSd6HgbgZYCFpWwSQ9BP4TDyQfqCiVEZFBM",
            "NULSd6Hghb6xH1dyRBeB8PEtMaq7mTVVobumu",
            "NULSd6HgXWexSgMsvt2nZMBP4J9rR25iwsSVK",
            "NULSd6HgcTYfYrXo8Dtw4jybwR9ufcWAne3Jd",
            "NULSd6HgiYNenDT7BRjZPvNqdUjp4KE7S8nhP",
            "NULSd6Hgac7JFS3D19KfGmgnSBk6S3Cpv6fJw",
            "NULSd6HgiaHGhV7QGhPWx2vZtGAadtGFP2Aig",
            "NULSd6HgW3VgpnKRAaneLqLEjTXtb8PnTUhu2",
            "NULSd6Hgbrxiq4Mhj66TBX6rG6nPQyiFSJ4VX",
            "NULSd6Hghcm7Z4QESTE5LQajR7nhqHfhcur7t",
            "NULSd6HgcEL7tX9vv2FqTnHcHezsorUfyxP2r",
            "NULSd6HgWuwrRMTKStouEcma1WgQmB8TDzGho",
            "NULSd6HgaxanMfRxci5mKWZNUH6NgvR8KhrDm",
            "NULSd6HgVjDUaGSprkb9yNF3yPzJafHKgEtPr",
            "NULSd6HgUh11m1MVQ1anHVwTkP8xZo59SggiU",
            "NULSd6Hgcxuj7DRJEks9t6wYQCA95RbbM3beG",
            "NULSd6Hgfg8P6dHDwPagNFsWJ3EWxT4THurEF",
            "NULSd6HgVDMcRUJjvT1DWXTM1wKEe6ZDXNVKW",
            "NULSd6HgWK7ZeFnVYmseFKYixYn5kRD9iBC87",
            "NULSd6HgUXRAoKTngDzencAFBcFjNmpq9ekam",
            "NULSd6HgbnJibFCFiBxYLfXtyE1bZofXiHZyT",
            "NULSd6HggmeGQsUSmPRc2Mc1b5KyDt73hxQrk",
            "NULSd6HgZKYqGJJCJ5avdyBTLgcznGyxmUd84",
            "NULSd6HgVx4yPaTuPbQjqAdSHx2twsAefJXMZ",
            "NULSd6HgZm9qdi1QDJhaKNbNXH9oTQYvns5DY",
            "NULSd6HgeivdcqzfgXVHsfwGzbMFC3HadW1Kk",
            "NULSd6HgVcuM6XV7WFz7ZnCvRm95AidKYxBn1",
            "NULSd6HgcWjC34v2GergvTTYrwZoofXoyeY2A",
            "NULSd6HghhKAAEoNjwW4quMk4qGiTby4ePjdv",
            "NULSd6Hgem5tFmKUab7qPAZJg65yrGsZEsPpB",
            "NULSd6HgTtjH8WZh4Vif6zcm2qxNGuk1D3Dd4",
            "NULSd6HggeP1VTRrNp4V8bwGLns5nFRsK1DW8",
            "NULSd6HgWVooymQqd2LYvgQhvurCi8SQXowL7",
            "NULSd6HghhxYxULByozjZ9aqpykhKw5FhQb2L",
            "NULSd6HgXToj6N6jEBtwYaaimnd3ui5r1Qmz7",
            "NULSd6HghB3jSroZZFuRtFJ4UQkUYTFVrn7Py",
            "NULSd6Hgbjfcr9JtbEYfTEKKSRrGrfhNyzdpj",
            "NULSd6HgcFqzzwUFVNJuozpxiimjwR3j6Wey5",
            "NULSd6HgWYstDgDmCJ1X3r6HHAtVrEyFbebFd",
            "NULSd6HgVQZxsdKZmTRe76vasM76F5Hwy9d7Z",
            "NULSd6HgVcURdTpG6mB38ye92EKmrRiw3Hx5R",
            "NULSd6HgejHtTAWTzBRNF4SWFb4qCkVM1Bzfg",
            "NULSd6HggfCSwUp3BfCE53eSeiciakChVn3vh",
            "NULSd6HgXoX9XWpRScLq7v68SvdUhNunSeQcN",
            "NULSd6HgePmLb9GJG1UvmdG9mb7fVYzg3uVJ6",
            "NULSd6Hgj2ktCsiAMhfo7DXXRt2Ta1xK1vQzy",
            "NULSd6HghCM8hjwNEEugT37m8dxvUBD5RU74d",
            "NULSd6HgcLzX3wu6fnTRGM2L5SkzLzKjiWaa6",
            "NULSd6HgerAM3nvtNn6YvRNZsBTZw9BGgewoU",
            "NULSd6HgbihwvD9j72YAmJjBcUTVz4ih6p39R",
            "NULSd6HgYpatuD5RUV584Lizkcq2rQDch6SD9",
            "NULSd6HgecNmBEGaN6RjqNmPWVud72de9tMRG",
            "NULSd6HgWepvVTf1DyMaeKzuC8z7x6t16Ag3x",
            "NULSd6HgYnJFKGZ5LbyrJ8y2XK7NM9swwdz9e",
            "NULSd6HgZPSpbSwmPE6a1S7cACRLLoBodHDWm",
            "NULSd6HgcVPnA24xb8Dxx5LnVFZBAzXspeEcw",
            "NULSd6HggyS8Z25aBrnxGWN3dyDs8kb7b5yJP",
            "NULSd6HgbvApntF9cpjwq23FWxdWzrJVRRBs3",
            "NULSd6HgUqJG3UAz1WoZSNmzAHGPe1D1FaXpv",
            "NULSd6Hgb2zwSQ8ZFZ9APEC3RxMaDrCA97zD4",
            "NULSd6HgVuCuY9Z68mrrc5aSuuTujen5w9mJX",
            "NULSd6HgYGKuS7qHPorfnW3awBQBQTKHcv3QZ",
            "NULSd6HgXrxSBvPfT5wnnofHkD1m9KFjHwzjK",
            "NULSd6Hgcys6eQDxCma8RKMtpxLQUXDCga2FV",
            "NULSd6HgUavegUe9RnYiG6ws11x2xYfCDWKwy",
            "NULSd6HgZ3UKSfmEer5zPy8HJieSnqFqye3J3",
            "NULSd6HggvpQENbGxwvyiSC7kSiAVmxoH1hZF",
            "NULSd6HgYiNb24prcMx6Awbm47c4LJSK7MDjh",
            "NULSd6HgXYwBikfFXnL29v97fMTs1kHW4KCvg",
            "NULSd6HggQtb9MF9uszmusPMUnbxMfPZVdwQy",
            "NULSd6HgjFGoVgYrv5vBTdTXMq2KrHP9GFBjp",
            "NULSd6Hgaxrh7CTkoHEP86VYf11AypL7bVxW8",
            "NULSd6HgaTaxKZADz8ctZJm4kxb4xNfon4UFK",
            "NULSd6HgjTXRKZLtjyHmHNGFdMVrfoyMMQgnt",
            "NULSd6HgfVA58DqZTiFqdHUuHjT1nVawMnoGr",
            "NULSd6HgeKfstVdQYCNvCVcg3BpJmk5VtfWeN",
            "NULSd6HghWdwMr9tH1DweM7MngNJ2GSTsVrsW",
            "NULSd6HgVXKQkdm2eP7zEZRaviGEPhTheJi1t",
            "NULSd6HgYRueoDRu17HM7vda6hjcasegyeMbb",
            "NULSd6HgXNqskL1tMmC5dL6h9izAEdPFxa4be",
            "NULSd6Hgierdw8WUkLegVpCYNdYBNi1SE2YX7",
            "NULSd6HgXcHqfxu9XJmHkqZXJy5sfbbbZWTPj",
            "NULSd6HgifNwDSvJQoTPG4YoKjiG3Sq41smn6",
            "NULSd6HghpCceRvxTbfsWGon31jmQJVZTL847",
            "NULSd6HgZiKFG3fZVRKBRswaFCCuAZpPHmW6Y",
            "NULSd6HggT8FVLPuQzVgAyEAFJGBQ1j8ezQH6",
            "NULSd6Hgb8rrTqEADGAJmKxtdaCSsUgfEZC6v",
            "NULSd6HgUA6reJsFdHSDnh1mWzVaKrbpN6L9q",
            "NULSd6HgXAyJpjL6Khsxemm3pntABGKUUZAZm",
            "NULSd6HgcLE6arZBEsdLvDgCxQNPMCPBbTg3y",
            "NULSd6HgXhb5rpcmHBCGS3fGChbEP7Z37tqGx",
            "NULSd6HgZMsoPwNcBi1XiH3Zgtcy3Tnt8vE65",
            "NULSd6HgiQTqCM3KWwkJweBA9p82NRuKeofSg",
            "NULSd6HgZ3AMXngRFHnFV8aDpB1mjTDk2Zmke",
            "NULSd6Hghn86Ww5o3wTxLR3My3Y1EmrtCMerL",
            "NULSd6HgURmSafCpTrLEiapUHtzrkhfz11HMp",
            "NULSd6HgcD3ucbS9gejAhvtP8F49GWbMT4UPY",
            "NULSd6Hgf1qnjR7Mq1Y7Fnuah1pDkYK1WYTAi",
            "NULSd6HgYYtopt163W8ETU21dnCS5s1YGsmvn",
            "NULSd6HgiEymBURDLprFjtptYd9MhDZY73nGj"};

}
